### ISSUE TITLE
Add new algorythm https://github.com/LingDong-/linedraw

### ISSUE THREAD

**Issue by svenhb** [mitxela/plotterfun#11]
Very nice collection!
Perhaps you could add this algorithm: https://github.com/LingDong-/linedraw

**Comment by mitxela** [comment]
Um.

I take it you didn't look too closely, but I already ported that algorithm, it was one of the first ones I did. Just under Delaunay in the drop-down box.

**Comment by svenhb** [comment]
Hmmm, but the results are different:
Example from https://github.com/LingDong-/linedraw#linedraw:
![image](https://user-images.githubusercontent.com/19973251/99561916-c8430c00-29c7-11eb-942a-0ab0dddf02ad.png)
Result with the Delaunay algorythm:
![image](https://user-images.githubusercontent.com/19973251/99562070-f4f72380-29c7-11eb-8077-397513b51dd8.png)

**Comment by svenhb** [comment]
Ok, I'm sorry. Linedraw does it - really embarrassing, it's also the same name :-)
![image](https://user-images.githubusercontent.com/19973251/99563218-523fa480-29c9-11eb-82ad-3e38b0f7eecc.png)
